name: Release Candidate

on:
  push:
    branches:
      - main

jobs:
  Tagging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Git Tag Version
        run: |
          git tag v${{ env.MAJOR }}.${{ env.MINOR }}.${{ env.PATCH }}.${{ env.REVISION }}
          git push origin v${{ env.MAJOR }}.${{ env.MINOR }}.${{ env.PATCH }}.${{ env.REVISION }}
        env:
          MAJOR: 0
          MINOR: 1
          PATCH: 0
          REVISION: ${{ github.run_number }}

  Build_Release:
    runs-on: ubuntu-latest
    needs: Tagging
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install npm packages
        run: |
          npm install -g yarn
          yarn

      - name: Build Vue 3 App
        run: yarn build

      - name: Archive build output
        run: |
          zip -r app.zip ./dist/
        working-directory: ${{ github.workspace }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: app.zip
          path: app.zip
